### ISSUE TITLE
Question: Purpose of "getOperationName" function

### ISSUE THREAD

**Issue by thosakwe** [snowballdigital/-flutter-graphql#11]
While looking through the source of this package, I found this comment:
https://github.com/snowballdigital/flutter-graphql/blob/master/lib/src/core/query_manager.dart#L67-L68:

```dart
// XXX there is a bug in the `graphql_parser` package, where this result might be
// null event though the operation name is present in the document
```

I am the creator/maintainer of the `graphql_parser` package. Can you provide some details about the bug you are referring to?

In a query like this:

```graphql
{
  foo,
  bar: baz
  ...quux
  ... on A {b, c}
}
```

There is no operation name, and this a pretty common case.

Is it possible that the query you were using simply didn't have an operation name? Otherwise, if you can provide a repro, I can fix it.

**Comment by juicycleff** [comment]
Hi @thosakwe I didn't write that part of the code
