### ISSUE TITLE
Is the project still being maintained?

### ISSUE THREAD

**Issue by chenxianqi** [snowballdigital/-flutter-graphql#14]
Is the project still being maintained?
I haven't seen it updated for a long time.

**Comment by juicycleff** [comment]
@chenxianqi yes it is being maintained. And yeah I recently relocated and didn't quite contribute much during for about 3 weeks, but I am more settled in now and fixing bugs. I will push here once my changes are safe to release

**Comment by chenxianqi** [comment]
> @chenxianqi yes it is being maintained. And yeah I recently relocated and didn't quite contribute much during for about 3 weeks, but I am more settled in now and fixing bugs. I will push here once my changes are safe to release

Thank you's contribution to the community.  good, I've closed it.
