### ISSUE TITLE
How to update cache after mutation without pollInterval?

### ISSUE THREAD

**Issue by Goolpe** [snowballdigital/-flutter-graphql#2]
Hello, Query gives old data after mutation - need new, how can I do this without pollInterval (because I can't to do much requests to the server)?

**Comment by juicycleff** [comment]
Hey, @Goolpe I would say the cache is not as fully functional as one might hope. I am rewriting the cache and some react apollo sugars for the next release. You are also more than welcome to contribute. I had to move to Norway early this week so I didn't have enough time to contribute. But I'm more settled in now. Should get some update this weekend.

**Comment by Goolpe** [comment]
Thank you, it would be awesome!
