### ISSUE TITLE
why not transfer ownership?

### ISSUE THREAD

**Issue by micimize** [snowballdigital/-flutter-graphql#4]
@juicycleff you can transfer repository ownership, which I think would be less confusing than copy-pasting for end-users, and maintain the github repo-relationship graph 
<img width="759" alt="Screen Shot 2019-03-19 at 18 52 25" src="https://user-images.githubusercontent.com/8343799/54649430-2e9bbc80-4a78-11e9-8ecf-888ae3b52b56.png">

**Comment by juicycleff** [comment]
Hey, @micimize Sorry had to relocate to Norway so was unavailable for a bit. How are you? Regarding your question Well, I will think about it though. Wil get back to you asap
