### ISSUE TITLE
Relies on an older version of path_provider

### ISSUE THREAD

**Issue by mainawycliffe** [snowballdigital/-flutter-graphql#8]
Would it be possible to update the path_provider dependency to the latest version, i am getting incompatible since it requires version ^0.4.1 and using Cached Network Image which is on version ^0.5.0+1. 

```
Because cached_network_image >=0.7.0 depends on flutter_cache_manager ^0.3.2 which depends on path_provider ^0.5.0+1, cached_network_image >=0.7.0 requires path_provider ^0.5.0+1.

And because flutter_graphql 1.0.0-rc.3 depends on path_provider ^0.4.1 and no versions of flutter_graphql match >1.0.0-rc.3 <2.0.0, cached_network_image >=0.7.0 is incompatible with flutter_graphql ^1.0.0-rc.3.
```

**Comment by juicycleff** [comment]
Sure I have already fixed this issue. It will be in the next release :)

**Comment by mainawycliffe** [comment]
That's great, thanks. 

Also, any way I can help, the community would really benefit from having a great GraphQL library for dart.
