### ISSUE TITLE
WANT TO BE A CORE CONTIBUTOR

### ISSUE THREAD

**Issue by juicycleff** [snowballdigital/-flutter-graphql#9]
Do you want to be a core contributor, please drop your names so we can discuss the way forward for the library. We need a very stable GraphQL library for Flutter.

**Comment by mainawycliffe** [comment]
I am interested

**Comment by Goolpe** [comment]
I'll be glad to help

**Comment by juicycleff** [comment]
Great, I think we should set out a day, talk as per moving on with adding more features and also about the graphql flutter community as well

**Comment by micimize** [comment]
@juicycleff I see [you've removed all mention of original development and contributors](https://github.com/snowballdigital/flutter-graphql/commit/4ef7613a332d4e80b10293993f672c5a097a5256), have broken the github history (#4), and are now actively seeking contributors.

This is very frustrating to me, as I've been pouring all the time I can into revitalizing `graphql-flutter`, largely to make this schism unnecessary

**Comment by Sewdn** [comment]
@juicycleff  @micimize Me and my colleagues are interested in contributing as a team, but we first need to assess what package is the most promising to end-up as the goto apollo client in dart. (cfr https://github.com/snowballdigital/flutter-graphql/issues/12) Thanks!
